# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eric Cloninger
email: ericc@pobox.com
description: Personal website  
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://ericcloninger.com" # the base hostname & protocol for your site
twitter_username: ericc
github_username: ehcloninger
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: <!--more-->


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/assets/images'
